export enum FrontendRoutes {
  Contact = 'contact',
  Login = 'login',
  Answers = 'answers',
  SearchQuestions = 'search-questions',
  RandomQuestion = 'random-question',
  Welcome = 'welcome',
  FAQ = 'faq',
  SignUp = 'signup',
  Onboarding = 'onboarding',
  MyQuestions = 'my-questions',
  MyRejectedQuestions = 'my-rejected-questions',
  Privacy = 'privacy',
  Imprint = 'imprint',
  Licenses = 'licenses',
  Terms = 'terms',
}
