name: Release Beta iOS

on:
  push:
    branches: [ 'develop' ]

jobs:
  build:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.1
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: echo '${{ secrets.APPSTORE_CONNECT_API_KEY }}' > /tmp/AuthKey_FLMC3H9H8X.p8
    - run: echo '${{ secrets.SENTRY_TOKEN }}' > ./sentry.properties
    - run: echo '${{ secrets.FCM_IOS_PLIST }}' > ./GoogleService-Info.plist
    - run: npm ci
    # create www folder to satisfy cordova
    - run: mkdir -p www
    - run: npm run apply-version
    - run: npm run ionic -- cordova resources ios
    - run: npm run cordova -- platform add ios
    - run: npm run ng -- run app:ionic-cordova-build:production --platform=ios
    - run: npm run cordova -- prepare ios --prod
    - run: bundle exec fastlane ios appcenter
      env:
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "iOS Release IPA"
        path: builds/plusme.ipa
    - run: npm run appcenter -- distribute release --file "builds/plusme.ipa" --group "Collaborators" --app "plusme-azure-2022-konten.tim.schumacher.im/me-iOS" --token "${IOS_APPCENTER_TOKEN}" --release-notes "${environment}"
      env:
        IOS_APPCENTER_TOKEN: ${{secrets.IOS_APPCENTER_TOKEN}}
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './www'
